### ISSUE TITLE
Offline editing and merge

### ISSUE THREAD

**Issue by dumblob** [kynan/dokuvimki#10]
Are there any plans to support offline editing and a consequent merge once one gets online again? I'm having the same use case as described on http://wiki.c2.com/?WikiSync .

Or do you have any recommendations?

**Comment by kynan** [comment]
I don't have any plans to work on this. However since dokuwiki is file based, you could run it locally and sync with a hosted version using rsync or some other file syncing mechanism.

**Comment by dumblob** [comment]
@kynan thanks for the response. It seems to me plain syncing is not much of an issue. But merging would require a handful of work in the user interface and probably the "business logic" behind. And that's why merging is my concern.

Any ideas?

**Comment by kynan** [comment]
I don't think DokuWiki is the best choice if you care about such complex use cases. I'm only a casual user myself and have not investigated this issue. You'll likely get better answers from the [DokuWiki user forum](http://forum.dokuwiki.org).

There seems to be a [sync plugin](https://www.dokuwiki.org/plugin:sync) and an [unmaintained merge plugin[(https://www.dokuwiki.org/plugin:conflictmerger).
