### ISSUE TITLE
Windows support(Backslashes)

### ISSUE THREAD

**Issue by MeyerFabian** [kynan/dokuvimki#14]
Hey i have just installed DokuVimKi for my local server.
Everything worked just fine until i wanted to :DWrite. 

Problematic are backslashes on windows:
https://github.com/MeyerFabian/dokuvimki/commit/6feda6f55925aa1d8c57f57de6eda2374c734932#diff-6c1a3cb81d4f5dc7f3b38b5760219fdbL349

**Comment by kynan** [comment]
Please send a PR
