### ISSUE TITLE
e to open link isn't remapped - moves cursor to end of word as usual

### ISSUE THREAD

**Issue by alazyworkaholic** [kynan/dokuvimki#15]
I'm referring to the final entry in EDIT-MAPPINGS of the dokuvimki help.
> e    opens a link under the current cursor position for editing (this mappings only works in normal mode)

I understand that if I open a wiki page in dokuvimki and place the cursor over a [[aPage|link to the page aPage]] then press e in normal mode the program should open aPage just as if I had issued the command `:DWedit aPage`
That doesn't happen. Instead, the cursor placed on the 'P' simply moves to the 'e' before the '|' when I press e.
I'm using neovim 0.3.4.

**Comment by kynan** [comment]
That was actually me: I changed this to `C-]` for consistency with expected behaviour in Vim in 022e44c8. Will update the documentation.
