### ISSUE TITLE
Feature Request - Navigate Backwards to last edited page

### ISSUE THREAD

**Issue by alazyworkaholic** [kynan/dokuvimki#16]
Feature Request: introduce two quick key-combos that would close the current buffer (one version to save, another to discard) and return to the last edited page.

Example:
DWedit page1
press e over `[[link to page2]]`
write [[page3|link to page 3]] in page2, save.
press e over `[[link to page3]]
press key-combo (CTRL-B?) to return to page2
press again to return to page1

**Comment by kynan** [comment]
You can actually do that already with `:brevious` `:bnext`. This will neither save or discard the current buffer though. Is that good enough for you?

**Comment by alazyworkaholic** [comment]
Yes, +1 for using vim's built-in methods. It makes perfect sense now that I'm part way up the learning clif. Solved.
