### ISSUE TITLE
Feature Request: Re-open index special buffer if closed.

### ISSUE THREAD

**Issue by alazyworkaholic** [kynan/dokuvimki#18]
I often open several buffers via DWedit or while editing other files via :e and eventually I'll end up closing the index special buffer by accident. I'd like to re-open it but the only way now is to restart DokuVimKi, which is a really productivity killer and very inconvenient if I have many buffers open for editing.

If that's already possible, then please just let me know how and add it to the documentation.

**Comment by kynan** [comment]
Have you tried running `DWcd` without arguments?

**Comment by alazyworkaholic** [comment]
I hadn't, but that solves my problem. Thanks.
