### ISSUE TITLE
Feature Request: Limit namespaces listed in index to those that are not empty

### ISSUE THREAD

**Issue by alazyworkaholic** [kynan/dokuvimki#20]
DokuVimKi shows namespaces for all pages in cyan at the top of the index buffer, even those that are only simple pages and are effectively empty as namespaces. I'd prefer to only see namespaces that contain pages instead of seeing even empty ones. I think it would make organization easier because it would be more readily apparent what entries are actually used as a namespace. It would also mirror the sitemap one views through a browser.

Could this be implemented as a configurable option?

**Comment by kynan** [comment]
This seems to be working as intended for me i.e. as you describe you'd like it to be: I have a list of namespaces in cyan at the top followed by a list of pages in the root namespace.

What do you see? Can you give more information about the layout of your wiki? Or a screenshot or similar?

**Comment by alazyworkaholic** [comment]
![Browser](https://user-images.githubusercontent.com/31052043/86501253-4b3f2f00-bd65-11ea-800c-6a554a251d58.png)
![DokuVimKi](https://user-images.githubusercontent.com/31052043/86501258-52fed380-bd65-11ea-8927-9164933d232b.png)
![DokuVimKi_emptyNS](https://user-images.githubusercontent.com/31052043/86501363-42029200-bd66-11ea-8e62-1136b121dfa3.png)

I've attached three screenshots. One is a view of the sitemap in a browser. You can see that there are just 8 "active" namespaces, ones that actually have a file inside, and the wiki's articles follow below. The others show DokuVimKi. One shows how cyan namespace entries fill my screen and another shows that my "android/" namespace is empty. I'd rather my DokuVimKi index pane's contents resemble the site map I see via a browser.

**Comment by kynan** [comment]
The sitemap shows you an "android" *page*, but DokuVimKi shows an "android" *namespace*. Does DokuVimKi show an android *page* too?

Also: on your wiki server, is there a directory called "android"? If so, does it still show up in DokuVimKi if you delete that directory?

**Comment by alazyworkaholic** [comment]
Yes, if I 'scrolled' down the index, I'd see an android page too.
At /var/www/alazysite/dokuwiki/data/pages/ I have android.txt but no android folder.

**Comment by kynan** [comment]
Thanks for reporting this. I can confirm I see the same behavior on my wiki and I found the behavior causing it and will be pushing a fix.
