### ISSUE TITLE
Document highlight groups

### ISSUE THREAD

**Issue by cvoltz** [kynan/dokuvimki#21]
It would be nice if the help documentation documented the supported highlight groups:
- DokuBlockColor
- DokuBold
- DokuCode
- DokuCodeGeneric
- DokuCodeMatch
- DokuDel
- DokuFile
- DokuFileGeneric
- DokuFileMatch
- DokuFootnote
- DokuFootnoteMatch
- DokuFormatColor
- DokuHeadline
- DokuImageMode
- DokuItalic
- DokuLink
- DokuLinkExternal
- DokuLinkInterwiki
- DokuLinkMail
- DokuLinkTitle
- DokuList
- DokuMedia
- DokuMonospaced
- DokuNewLine
- DokuNoWiki
- DokuQuote
- DokuRule
- DokuSmileys
- DokuSub
- DokuSup
- DokuTableTD
- DokuTableTH
- DokuUnderlined

**Comment by kynan** [comment]
Sure. Could you describe how you'd like this documentation to look like? Happy to accept a pull request also :)

**Comment by cvoltz** [comment]
I think all that is needed is to add a section that:

- mentions the style of elements _can_ be configured
- provides a simple list of the elements (since what they modify is self-evident)
- provides a simple example of customizing an element 
- provides a link to the VIM docs on `highlight` command

**Comment by kynan** [comment]
Let me know if that meets your requirements!

**Comment by cvoltz** [comment]
LGTM. Thanks.
