### ISSUE TITLE
DokuVimKi fails to do anything after initial load due to NameError

### ISSUE THREAD

**Issue by zpuskas** [kynan/dokuvimki#25]
System: Linux-5.15.12-gentoo-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-glibc2.34
vim version: 8.2.3741
python version: 3.9.9

vim is compiled with Python support as per `emerge --info`:

```
app-editors/vim-8.2.3741::gentoo was built with the following:
USE="X acl crypt gpm nls python -cscope -debug -lua -minimal -perl -racket -ruby (-selinux) -sound -tcl -terminal -vim-pager" ABI_X86="(64)" LUA_SINGLE_TARGET="lua5-1 -luajit" PYTHON_SINGLE_TARGET="python3_9 -python3_10 -python3_8"
```

Plug-in was downloaded via git clone (i.e. master:HEAD version) and all files copied to ~/.vim/ as well as .vimrc options set.

When launched with via `vim +DokuVimKi` I get the following error:

```
Error detected while processing command line..command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/plugin/dokuvimki.py", line 92, in __init__
    self.help()
  File "/home/user/.vim/plugin/dokuvimki.py", line 639, in help
    vim.command('help dokuvimki')
vim.error: Vim(help):E149: Sorry, no help for dokuvimki
Press ENTER or type command to continue
```

After pressing Enter the left pane opens and lists the top level namespace `ns:` correctly (i.e. connection is working to the DokuWiki server). However trying to edit a page either with `:DWedit page` or by switching to the left pane with `Ctrl-W <-` and selecting one I get the following error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'dokuvimki' is not defined
Press ENTER or type command to continue
```

Quitting vim also becomes impossible at this point as the above error message just keeps repeating no matter what command I try, and I have to go to another terminal and do `killall vim` (or equivalent).

**Comment by kynan** [comment]
Both errors seem to suggest that the plugin wasn't installed correctly. I strongly suggest installing using a plugin manager like vim-plug. Could you try that, just to rule out it's an installation issue?

I'm on vim 8.1 built with Python 3.8.7. Meanwhile I'll attempt to reproduce your issue with a "plain" installation of the plugin.

**Comment by kynan** [comment]
FWIW, I can't reproduce your issue using this Dockerfile:
```Dockerfile
FROM alpine:3.15

ARG SERVICE_USER
ARG SERVICE_HOME
ARG GID
ARG UID

ENV SERVICE_USER ${SERVICE_USER:-vim}
ENV SERVICE_HOME ${SERVICE_HOME:-/home/${SERVICE_USER}}
ENV GID ${GID:-1000}
ENV UID ${UID:-1000}

RUN \
  apk add --no-cache \
    py3-pip \
    python3 \
    shadow \
    vim && \
  /usr/sbin/groupadd -g ${GID} ${SERVICE_USER} && \
  /usr/sbin/useradd -d ${SERVICE_HOME} -s /bin/sh -g ${GID} -u ${UID} ${SERVICE_USER} && \
  pip3 install dokuwikixmlrpc

USER    ${SERVICE_USER}
WORKDIR ${SERVICE_HOME}
VOLUME  ${SERVICE_HOME}

ENTRYPOINT [ "/usr/bin/vim" ]
CMD [ "+DokuVimKi" ]
```
And then running it as follows works absolutely fine for me:
```bash
docker build -t alpine-vim-python
docker run -it -v /path/to/dokuvimki/clone:/home/vim/.vom -v $HOME/.vimrc:/home/vim/.vimrc alpine-vim-python
```

**Comment by zpuskas** [comment]
Thanks for the pointers. I usually dislike plug-ins that will download arbitrary code to my host, but for the sake of debugging I've tried vim-plug temporarily and indeed the DokuVimKi has worked as advertised. This has helped me to track down the issue with the manual installation though.

When manually installing the plug-in one has to merge the doc/tags file with any existing doc/tags file already in .vim directory that may have come with another plug-in before. In my case the tags file belonged to the taglist plug-in. After appending the tags file content (can just do `cat dokuvimki/doc/tags >> .vim/doc/tags`) from this repository to the existing tags file both taglist and DokuVimKi work well.

So I guess the only thing needs updating are the installation instructions in the README.md.

**Comment by kynan** [comment]
Thanks for reporting, I've just added a note to the README. If that is satisfactory, feel free to close this issue.

**Comment by zpuskas** [comment]
Thanks for the updated docs.
