### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kynan** [kynan/dokuvimki#7]
In Ubuntu 16.04 LTS, vim is build with `+python3` rather than `+python`. DokuVimKi should work with either!

**Comment by alazyworkaholic** [comment]
If python3 support isn't available, could you provide instructions on how to make vim use the python2 provider? I got the plugin to work (with neovim) but only by putting `g:loaded_python3_proider = 1` which totally disables it but of course I'd like to use python2 for this plugin only.

**Comment by kynan** [comment]
What happens when you try running the plugin in a vim with `+python3`? I don't currently have a way to test, however I thought I had fixed the incompatibilities.

**Comment by alazyworkaholic** [comment]
Nvim seems to work normally without DokuVimKi.
`echo has('python')` and `echo has('python3')` both return `1`.

First, I extract DokuVimKi to `~/.local/share/nvim/site/pack/dokuvimki`
This error appears when I run `nvim` from my shell (bash or zsh)
`
Error  detected while processing funciton provider#python3#Call:

line   18:
Traceback (most recent call alst):
    File "<string>", line 15, in <module>
    File "/usr/local/lib/python3.7/dist-packages/dokuwikixmlrpc.py", line 114
        except xmlrpclib.Fault, fault:
                                        ^
SyntaxError: invalid syntax
Press ENTER or type command to continue
`
Pressing Enter loads the neovim intro screen.

If I run `nvim +python3` the same error above appears but when I press enter this other error message appears before I get to the intro screen:
`
Error detected while processing command line:
E471: Argument required
Press ENTER or type command to continue
`

Next I place `g:loaded_python3_provider = 1` in my file (see it at http://paste.ubuntu.com/p/PH8GhTSbQV )

If I run `nvim` with that line above to disable python3, DokuVimKi works correctly and no error messages appear but `:echo has('python3')` -> 0, and `:python3 print('hello')` returns an error (as expected).

If I then run `nvim +python3` the E471 error message appears on its own and python3 remains disabled.

I tried debugging with `nvim -D` but couldn't make much sense of it.

**Comment by alazyworkaholic** [comment]
Looking over my error messages, I noticed the plugin was trying to process `/usr/local/lib/python3.7/dist-packages/dokuwikixmlrpc.py`. That would require python3 code and the code in that file was plainly python2 (with `print xyz` statements).
I had downloaded that from [pypi](https://pypi.org/project/dokuwikixmlrpc/#files) via ubuntu's pip/pip3.

Only then did I find [the file modified by kynan](https://github.com/kynan/dokuwikixmlrpc) The python2 code of this file appears modified to work with the python3 interpreter.

Sure enough, I had pip uninstall the pypi versions and then manually copied the fixed file into python3.7/dist-packages (there's got to be a better way - I don't know it). DokuVimKi now works, as does python3 at the same time.

If you have control of that pypi package can you update the file there? Or at least make a note in the readme that the pypi version is out of date?

So happy this works now.

**Comment by kynan** [comment]
You can install Python packages directly from GitHub:
```
pip install git+https://github.com/kynan/dokuwikixmlrpc
```
I'll update the README, thanks for flagging!

**Comment by kynan** [comment]
For completeness: I do have control of the dokuwikixmlrpc package by now and have since release a few new versions.
